### ISSUE TITLE
Screen keeps popping up to front

### ISSUE THREAD

**Issue by ThaTim** [phdelodder/SubTools#67]
The MultiSubDownloader BETA4 keeps popping up on to the front when it is scanning for available subtitles. This is annoying when I'm browsing. It doesn't happen when I minimize the program. 

Also look at the double row of the downloaded subtitle

Here's my log.

Controleren voor nieuwe update
Error: -------
java.lang.NumberFormatException: For input string: "0-BETA4"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.valueOf(Unknown Source)
	at org.lodder.subtools.multisubdownloader.UpdateAvailableDropbox.compareVersions(UpdateAvailableDropbox.java:96)
	at org.lodder.subtools.multisubdownloader.UpdateAvailableDropbox.check(UpdateAvailableDropbox.java:68)
	at org.lodder.subtools.multisubdownloader.UpdateAvailableDropbox.checkProgram(UpdateAvailableDropbox.java:33)
	at org.lodder.subtools.multisubdownloader.GUI.checkUpdate(GUI.java:127)
	at org.lodder.subtools.multisubdownloader.GUI.<init>(GUI.java:121)
	at org.lodder.subtools.multisubdownloader.App$1.run(App.java:102)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
-------
RateLimiet is bereikt voor 'www.addic7ed.com', gelieve 0 min en 15 sec te wachten
Error: Error response: 404 For url: http://www.addic7ed.com/serie/south_park/18/9/#rehash
Error: Error response: 404 For url: http://www.addic7ed.com/serie/south_park/18/10/#happyholograms
----- Download Options ------
 - OptionsAlwaysConfirm : true
-----------------------------
Downloading subtitle: Elementary - 03x15 - When Your Number's Up DIMENSION Vertaling: Het Elementary Team for release: Elementary.S03E15.When.Your.Numbers.Up.720p.HDTV.x264-DIMENSION.mkv
Downloading subtitle: Elementary - 03x15 - When Your Number's Up DIMENSION Vertaling: Het Elementary Team for release: Elementary.S03E15.When.Your.Numbers.Up.720p.HDTV.x264-DIMENSION.mkv
Downloading subtitle: Marvel's Agent Carter - 01x07 - Snafu 720p KILLERS Quality over Quantity (QoQ) Releases  Vertaling: Big0Bertha, M@rsman & Bee-TeeVee  Controle: SwagBoy for release: Marvels.Agent.Carter.S01E07.Snafu.720p.HDTV.x264-KILLERS.mkv
Downloading subtitle: Marvel's Agent Carter - 01x07 - Snafu 720p KILLERS Quality over Quantity (QoQ) Releases  Vertaling: Big0Bertha, M@rsman & Bee-TeeVee  Controle: SwagBoy for release: Marvels.Agent.Carter.S01E07.Snafu.720p.HDTV.x264-KILLERS.mkv
Downloading subtitle: Stalker - 01x16 - Salvation LOL for release: Stalker.S01E16.Salvation.720p.HDTV.x264-DIMENSION.mkv
Downloading subtitle: Stalker - 01x16 - Salvation LOL for release: Stalker.S01E16.Salvation.720p.HDTV.x264-DIMENSION.mkv
Downloading subtitle: The 100 - 02x13 - Resurrection 720p KILLERS Quality over Quantity (QoQ) Releases  Vertaling: FuBre  ~ Controle: CheckDude for release: The.100.S02E13.Resurrection.720p.HDTV.x264-KILLERS.mkv
Downloading subtitle: The 100 - 02x13 - Resurrection 720p KILLERS Quality over Quantity (QoQ) Releases  Vertaling: FuBre  ~ Controle: CheckDude for release: The.100.S02E13.Resurrection.720p.HDTV.x264-KILLERS.mkv
Downloading subtitle: The Flash (2014) - 01x14 - Fallout LOL Vertaling: Dream, Big0Bertha & SkeletorControle: MrZazou for release: The.Flash.2014.S01E14.Fallout.720p.HDTV.x264-DIMENSION.mkv
Downloading subtitle: The Flash (2014) - 01x14 - Fallout LOL Vertaling: Dream, Big0Bertha & SkeletorControle: MrZazou for release: The.Flash.2014.S01E14.Fallout.720p.HDTV.x264-DIMENSION.mkv

**Comment by phdelodder** [comment]
So there are 2 issues:
[] Subtitles are downloaded twice
[] Window is popping to the front when a search is in progress, when using an other window

**Comment by ThaTim** [comment]
Both issues are solved with version 1.0.2.
